// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxw4qD07wm65wQbmnSFENykYohXSKSYE',
    appId: '1:84913921901:web:99d363c4da890d16f14464',
    messagingSenderId: '84913921901',
    projectId: 'convey-dfd9d',
    authDomain: 'convey-dfd9d.firebaseapp.com',
    storageBucket: 'convey-dfd9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6P2c3dDyaeOXglYI8BbvJjDS2h6VjEM0',
    appId: '1:84913921901:android:4a4dbcd0a89cca8bf14464',
    messagingSenderId: '84913921901',
    projectId: 'convey-dfd9d',
    storageBucket: 'convey-dfd9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxNd3zINSdiM0Drs1pe760yEhBJeE3fwU',
    appId: '1:84913921901:ios:e2f59207174abbe3f14464',
    messagingSenderId: '84913921901',
    projectId: 'convey-dfd9d',
    storageBucket: 'convey-dfd9d.firebasestorage.app',
    iosBundleId: 'com.example.convey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxNd3zINSdiM0Drs1pe760yEhBJeE3fwU',
    appId: '1:84913921901:ios:e2f59207174abbe3f14464',
    messagingSenderId: '84913921901',
    projectId: 'convey-dfd9d',
    storageBucket: 'convey-dfd9d.firebasestorage.app',
    iosBundleId: 'com.example.convey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvxw4qD07wm65wQbmnSFENykYohXSKSYE',
    appId: '1:84913921901:web:0213f3ec194aa09cf14464',
    messagingSenderId: '84913921901',
    projectId: 'convey-dfd9d',
    authDomain: 'convey-dfd9d.firebaseapp.com',
    storageBucket: 'convey-dfd9d.firebasestorage.app',
  );
}
